"""initial schema

Revision ID: 96834293295b
Revises: 
Create Date: 2026-10-03 01:49:33.550251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96834293295b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('tail', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('yimu_account', sa.String(length=64), nullable=False),
    sa.Column('id_prefix', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_classification_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('merchant', sa.String(length=256), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=False),
    sa.Column('flow', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_classification_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_classification_cache_cache_key'), ['cache_key'], unique=True)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_job_id'), ['job_id'], unique=False)

    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_key', sa.String(length=256), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.create_index('ix_classification_rules_key', ['match_key'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_username'), ['username'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('job_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('stored_name', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('detected_source', sa.String(length=32), nullable=False),
    sa.Column('password_ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_files_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_files_job_id'), ['job_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('platform_uids', sa.JSON(), nullable=False),
    sa.Column('bank_uids', sa.JSON(), nullable=False),
    sa.Column('original_uids', sa.JSON(), nullable=False),
    sa.Column('refund_uids', sa.JSON(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('time_delta_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_job_id'), ['job_id'], unique=False)

    op.create_table('refund_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('refund_uid', sa.String(length=300), nullable=False),
    sa.Column('original_uid', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'refund_uid', name='uq_refund_override')
    )
    with op.batch_alter_table('refund_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_overrides_job_id'), ['job_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('record_uid', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('datetime', sa.String(length=24), nullable=False),
    sa.Column('flow', sa.String(length=8), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('signed_amount_cents', sa.Integer(), nullable=False),
    sa.Column('net_amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('disposition_reason', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(length=256), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('payment_method', sa.String(length=128), nullable=False),
    sa.Column('raw_type', sa.String(length=64), nullable=False),
    sa.Column('refund_original_uid', sa.String(length=300), nullable=True),
    sa.Column('refund_uids', sa.JSON(), nullable=False),
    sa.Column('refund_total_cents', sa.Integer(), nullable=False),
    sa.Column('matched_uids', sa.JSON(), nullable=False),
    sa.Column('match_ids', sa.JSON(), nullable=False),
    sa.Column('review_reasons', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=False),
    sa.Column('basis', sa.String(length=64), nullable=False),
    sa.Column('classification_state', sa.String(length=16), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('import_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'record_uid', name='uq_tx_job_uid')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_amount_cents'), ['amount_cents'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_classification_state'), ['classification_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_datetime'), ['datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_disposition'), ['disposition'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant'), ['merchant'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source'), ['source'], unique=False)
        batch_op.create_index('ix_tx_job_datetime', ['job_id', 'datetime'], unique=False)
        batch_op.create_index('ix_tx_job_disposition', ['job_id', 'disposition'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_job_disposition')
        batch_op.drop_index('ix_tx_job_datetime')
        batch_op.drop_index(batch_op.f('ix_transactions_source'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant'))
        batch_op.drop_index(batch_op.f('ix_transactions_disposition'))
        batch_op.drop_index(batch_op.f('ix_transactions_datetime'))
        batch_op.drop_index(batch_op.f('ix_transactions_classification_state'))
        batch_op.drop_index(batch_op.f('ix_transactions_amount_cents'))

    op.drop_table('transactions')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('refund_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_overrides_job_id'))

    op.drop_table('refund_overrides')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_job_id'))

    op.drop_table('matches')
    with op.batch_alter_table('job_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_files_job_id'))
        batch_op.drop_index(batch_op.f('ix_job_files_fingerprint'))

    op.drop_table('job_files')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_username'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_classification_rules_key')

    op.drop_table('classification_rules')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_job_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_classification_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_classification_cache_cache_key'))

    op.drop_table('ai_classification_cache')
    op.drop_table('account_mappings')
    # ### end Alembic commands ###
